version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: flask_postgres_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: flask_enterprise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de la Aplicación API Flask
  web:
    build: .
    container_name: flask_api_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/flask_enterprise_db
      - JWT_SECRET_KEY=clave_secreta_super_segura_123
      - FLASK_ENV=development
    depends_on:
      - db

volumes:
  postgres_data: